### ISSUE TITLE
SPI init

### ISSUE THREAD

**Issue by GLC-Kazetani** [swharden/FtdiSharp#6]
Hello, Swharden

How do I set the SPI clock, phase, and bit rate?

Kind Regards.

**Comment by swharden** [comment]
Hi @GLC-Kazetani, I think those values are currently hard-coded in the `I2C` class but you could copy its source code and modify those values if/as desired

https://github.com/swharden/FtdiSharp/blob/146cfb80db8a3280a8bbae866464d098c1075aa9/src/FtdiSharp/Protocols/I2C.cs#L46-L71

If you think it would be useful to allow users to modify those values, we could make them arguments of the `FTDI_ConfigureMpsse()` method and make it public so users could call it themselves with their own arguments.

Hope this helps!
