### ISSUE TITLE
I2C write mutiple bytes

### ISSUE THREAD

**Issue by AllenLius** [swharden/FtdiSharp#7]
when writing multiple bytes, only one byte is sent out.

**Comment by swharden** [comment]
Hi @AllenLius, thanks for this feedback!

This looks all right to me. Can you clarify what method is demonstrating the unexpected behavior?

https://github.com/swharden/FtdiSharp/blob/20b3dbf50a740b9bc6995ca20a79dbba0614b47b/src/FtdiSharp/Protocols/I2C.cs#L259-L276

**Comment by AllenLius** [comment]
Hi @swharden,
I can't reproduce this issue after upgrading to Win11.
