### ISSUE TITLE
Can I use GPIO and SPI at the same time?

### ISSUE THREAD

**Issue by GLC-Kazetani** [swharden/FtdiSharp#8]
Hi, swharden.

Can I use GPIO and SPI at the same time?
Or will it can't use with FTD2XX too?

```C#
            FtdiDevice device = FtdiDevices.First();  
            GPIO gpio = new GPIO(device);
            SPI spi = new SPI(device, spiMode: 1, slowDownFactor: 1);   // Error
```

Kind regards.

**Comment by swharden** [comment]
Hi @GLC-Kazetani, with the current design of this software I think both the `GPIO` and `SPI` classes fully take over the FTDI device to achieve their communication.

SPI and GPIO should be possible to run at the same time. You can copy the `SPI` class into your own class named something like `SpiWithGpio` and add the GPIO functions from the `GPIO` class and I suspect it will work:

https://github.com/swharden/FtdiSharp/blob/146cfb80db8a3280a8bbae866464d098c1075aa9/src/FtdiSharp/Protocols/GPIO.cs#L56-L81

If it does work as expected let me know and I can add those functions into the SPI and I2C classes too (or perhaps in the `ProtocolBase` class), so GPIO functionality will be available everywhere. If you decide to give this a go, I'd be happy to review and merge a pull request in good time 👍
